// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhRm691GSq8RNWJD--oip3W4jTOKQuTV4',
    appId: '1:750886815306:web:38ed63ac666c3f9310c8b3',
    messagingSenderId: '750886815306',
    projectId: 'quick-chat-9c290',
    authDomain: 'quick-chat-9c290.firebaseapp.com',
    storageBucket: 'quick-chat-9c290.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChF3e4bDJ-uWZq-QLZWGKBYQbu-Vntn48',
    appId: '1:750886815306:android:db7ad17a55bcdfe110c8b3',
    messagingSenderId: '750886815306',
    projectId: 'quick-chat-9c290',
    storageBucket: 'quick-chat-9c290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Of748jH_HZOTMyLWO9Y40cWC1_3dLSo',
    appId: '1:750886815306:ios:78626f4ceae3386810c8b3',
    messagingSenderId: '750886815306',
    projectId: 'quick-chat-9c290',
    storageBucket: 'quick-chat-9c290.appspot.com',
    iosBundleId: 'com.thapaalish.quickchat.quickchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Of748jH_HZOTMyLWO9Y40cWC1_3dLSo',
    appId: '1:750886815306:ios:78626f4ceae3386810c8b3',
    messagingSenderId: '750886815306',
    projectId: 'quick-chat-9c290',
    storageBucket: 'quick-chat-9c290.appspot.com',
    iosBundleId: 'com.thapaalish.quickchat.quickchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhRm691GSq8RNWJD--oip3W4jTOKQuTV4',
    appId: '1:750886815306:web:cc0d0a02eb5d286a10c8b3',
    messagingSenderId: '750886815306',
    projectId: 'quick-chat-9c290',
    authDomain: 'quick-chat-9c290.firebaseapp.com',
    storageBucket: 'quick-chat-9c290.appspot.com',
  );
}
